In [1]:
!pip install --upgrade pandas

Collecting pandas
  Using cached pandas-2.3.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.23.2 (from pandas)
  Using cached numpy-2.3.4-cp311-cp311-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kanna\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\kanna\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.3.3-cp311-cp311-win_amd64.whl (11.3 MB)
Using cached numpy-2.3.4-cp311-cp311-win_amd64.whl (13.1 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.3.4 pandas-2.3.3 pytz-2025.2 tzdata-2025.2

[notice] A new release of pip is available: 24.0 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
df = pd.read_csv(r"C:\Users\kanna\Downloads\amazon_india_complete_2015_2025.csv.csv")

In [5]:
df

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,TXN_2023_00063013,2023-07-23,CUST_2023_00018393,PROD_000454,Vivo Y95 64GB Black,Electronics,Smartphones,Vivo,27340.84,21.57,...,False,NaN,4.0,Delivered,7,2023,3,0.20,True,3.5
1,TXN_2021_00064486,20-07-2021,CUST_2015_00002865,PROD_000579,Realme Realme 3 128GB Black,Electronics,Smartphones,Realme,32907.49,0.00,...,False,NaN,5/5,Delivered,7,2021,3,0.21,False,4.5
2,TXN_2017_00065617,2017-11-16,CUST_2016_00004057,PROD_000295,Vivo V7 32GB Blue,Electronics,Smartphones,Vivo,"47,052.18",21.91,...,False,NaN,5.0,Delivered,11,2017,4,0.24,True,4.3
3,TXN_2020_00054393,2020-05-04,CUST_2020_00014574,PROD_001654,Alienware Pavilion 4GB RAM Silver,Electronics,Laptops,Alienware,238725.44,59.60,...,True,Summer Sale,5.0 stars,Delivered,5,2020,2,1.85,Yes,3.6
4,TXN_2018_00071646,2018-10-09,CUST_2018_00006275,PROD_000095,Motorola Moto X Play 16GB White,Electronics,Smartphones,Motorola,25970.76,0.00,...,False,NaN,4.0,Delivered,10,2018,4,0.16,False,3.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1127604,TXN_2018_00047331,2018-07-06,CUST_2017_00025689,PROD_000009,Apple iPhone 6 Plus 16GB Black,Electronics,Smartphones,Apple,134278.16,30.83,...,True,Back to School,5.0,Delivered,7,2018,3,0.17,True,3.6
1127605,TXN_2022_00065321,2022-07-23,CUST_2021_00026763,PROD_001732,OnePlus iPad 8GB RAM Silver,Electronics,Tablets,OnePlus,97578.76,0.00,...,False,NaN,4.5,Delivered,7,2022,3,0.58,True,4.6
1127606,TXN_2023_00057908,01-07-2023,CUST_2023_00031035,PROD_001572,ASUS Inspiron 8GB RAM Black,Electronics,Laptops,ASUS,105284.29,43.31,...,True,Back to School,4.0,Delivered,7,2023,3,1.37,True,4.2
1127607,TXN_2020_00035169,2020-04-12,CUST_2017_00005760,PROD_001582,ASUS Gaming 8GB RAM Silver,Electronics,Laptops,ASUS,"Rs 72,687",0.00,...,False,NaN,5.0,Delivered,4,2020,2,2.02,False,3.8
1127608,TXN_2022_00124835,2022-12-06,CUST_2022_00042212,PROD_001764,JBL Gaming Headset,Electronics,Audio,JBL,7092.55,0.00,...,False,NaN,5.0,Delivered,12,2022,4,0.71,True,3.3

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1127609 entries, 0 to 1127608
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   transaction_id          1127609 non-null  object
 1   order_date              1127609 non-null  object
 2   customer_id             1127609 non-null  object
 3   product_id              1127609 non-null  object
 4   product_name            1127609 non-null  object
 5   category                1127609 non-null  object
 6   subcategory             1127609 non-null  object
 7   brand                   1127609 non-null  object
 8   original_price_inr      1127609 non-null  object
 9   discount_percent        1127609 non-null  float64
 10  discounted_price_inr    1127609 non-null  float64
 11  quantity                1127609 non-null  int64
 12  subtotal_inr            1127609 non-null  float64
 13  delivery_charges        1037408 non-null  float64
 14  final_amount_inr        1127609 non-null  float64
 15  customer_city           1127609 non-null  object
 16  customer_state          1127609 non-null  object
 17  customer_tier           1127609 non-null  object
 18  customer_spending_tier  1127609 non-null  object
 19  customer_age_group      992294 non-null   object
 20  payment_method          1127609 non-null  object
 21  delivery_days           1127609 non-null  object
 22  delivery_type           1127609 non-null  object
 23  is_prime_member         1127609 non-null  object
 24  is_festival_sale        1127609 non-null  object
 25  festival_name           349873 non-null   object
 26  customer_rating         785913 non-null   object
 27  return_status           1127609 non-null  object
 28  order_month             1127609 non-null  int64
 29  order_year              1127609 non-null  int64
 30  order_quarter           1127609 non-null  int64
 31  product_weight_kg       1127609 non-null  float64
 32  is_prime_eligible       1127609 non-null  object
 33  product_rating          1127609 non-null  float64
dtypes: float64(7), int64(4), object(23)
memory usage: 292.5+ MB

In [7]:
df.isnull().sum().sort_values()

transaction_id                 0
order_date                     0
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr             0
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
final_amount_inr               0
customer_city                  0
customer_state                 0
order_quarter                  0
customer_tier                  0
customer_spending_tier         0
payment_method                 0
delivery_type                  0
delivery_days                  0
is_prime_member                0
is_festival_sale               0
product_weight_kg              0
return_status                  0
order_year                     0
order_month                    0
product_rating                 0
is_prime_eligible              0
delivery_charges           90201
customer_age_group        135315
customer_rating           341696
festival_name             777736
dtype: int64

In [8]:
pd.to_datetime(..., errors='coerce')

NaT

In [9]:
pd.to_datetime(df['order_date'], errors='coerce').isna().sum()

np.int64(108256)

In [10]:
bad_dates = df.loc[pd.to_datetime(df['order_date'], errors='coerce').isna(), 'order_date'].drop_duplicates().sample(50, random_state=1)
print(bad_dates.tolist())

['14-06-2024', '24/04/2023', '04/30/2021', '13-06-2023', '09-03-2025', '07/24/2022', '01/21/2020', '07-03-2022', '22-07-2021', '21/07/2024', '21/08/2021', '07/27/2016', '22/11/2018', '13/10/2025', '29-03-2017', '11/17/2025', '03/25/2022', '19/06/2024', '17-12-2023', '11/20/2016', '14/05/2022', '09-12-2023', '04/16/2016', '09/11/2024', '16/05/2020', '30/11/2021', '14/08/2025', '18/09/2015', '09/04/2015', '12/20/2022', '31/03/2025', '02/27/2022', '30-11-2015', '11/01/2022', '01-04-2021', '18-10-2022', '12-03-2019', '03/21/2018', '10/03/2018', '27/10/2024', '26-03-2016', '20/01/2021', '20/03/2020', '27-06-2016', '01/22/2023', '18-09-2019', '05/07/2025', '13/02/2016', '22/12/2025', '23-07-2024']

In [11]:
vals = df['order_date'].astype(str)
import re
def pattern(s):
    if re.match(r'^\d{4}-\d{2}-\d{2}', s): return 'YYYY-MM-DD'
    if re.match(r'^\d{2}/\d{2}/\d{4}', s): return 'DD/MM/YYYY'
    if re.match(r'^\d{2}-\d{2}-\d{4}', s): return 'DD-MM-YYYY'
    if re.search(r'[A-Za-z]', s): return 'text-month'
    if re.match(r'^\d{8}$', s): return 'DDMMYYYY'
    return 'other'
pat_series = vals[pd.to_datetime(df['order_date'], errors='coerce').isna()].apply(pattern)
pat_series.value_counts()

order_date
DD/MM/YYYY    67893
DD-MM-YYYY    40363
Name: count, dtype: int64

In [12]:
s = df['order_date'].astype(str)

# Parse common day-first formats
mask = s.str.match(r'^\d{2}/\d{2}/\d{4}$', na=False)
df.loc[mask, 'order_date'] = pd.to_datetime(s[mask], format='%d/%m/%Y', dayfirst=True, errors='coerce')

mask = s.str.match(r'^\d{2}-\d{2}-\d{4}$', na=False)
df.loc[mask, 'order_date'] = pd.to_datetime(s[mask], format='%d-%m-%Y', dayfirst=True, errors='coerce')

# Parse any remaining with inference (covers MM/DD/YYYY already handled earlier if present)
df['order_date'] = pd.to_datetime(df['order_date'].fillna(s), infer_datetime_format=True, dayfirst=True, errors='coerce')

# Check remaining failures
df['order_date'].isna().sum()

C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\3587513603.py:11: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  df['order_date'] = pd.to_datetime(df['order_date'].fillna(s), infer_datetime_format=True, dayfirst=True, errors='coerce')
C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\3587513603.py:11: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['order_date'] = pd.to_datetime(df['order_date'].fillna(s), infer_datetime_format=True, dayfirst=True, errors='coerce')

np.int64(16466)

In [13]:
bad = df.loc[df['order_date'].isna(), 'order_date'].astype(str).drop_duplicates().sample(50, random_state=1)
print(bad.tolist())

ValueError: Cannot take a larger sample than population when 'replace=False'

In [14]:
bad_vals = df.loc[df['order_date'].isna(), 'order_date'].astype(str).drop_duplicates()
len_bad = len(bad_vals)
bad_sample = bad_vals.sample(n=min(50, len_bad), random_state=1).tolist()
print(bad_sample)

['NaT']

In [15]:
bad_vals.tolist()

['NaT']

In [16]:
# if you kept raw column
bad_raw = df.loc[df['order_date'].isna(), 'order_date_raw'].drop_duplicates().tolist()
print(bad_raw)

KeyError: 'order_date_raw'

In [17]:
import pandas as pd

# adjust path if needed
path = r"C:\Users\kanna\Downloads\amazon_india_complete_2015_2025.csv.csv"

# load only order_date to speed up
raw = pd.read_csv(path, usecols=['order_date'], dtype=str)

# find rows that pandas can't parse
mask_bad = pd.to_datetime(raw['order_date'], errors='coerce').isna()

# unique problematic strings
bad_vals = raw.loc[mask_bad, 'order_date'].drop_duplicates().tolist()
len(bad_vals), bad_vals[:200]   # shows count and first 200 examples

(10399,
 ['20-07-2021',
  '02-12-2023',
  '12/10/2017',
  '29-04-2018',
  '04/11/2016',
  '12/02/2020',
  '05-08-2016',
  '12-09-2016',
  '10/10/2022',
  '21-12-2021',
  '08/16/2023',
  '11-09-2024',
  '01-08-2022',
  '09/26/2020',
  '14-01-2019',
  '10/18/2023',
  '11/14/2018',
  '04/12/2022',
  '07/22/2023',
  '09/05/2025',
  '07/12/2018',
  '02/09/2020',
  '16/03/2023',
  '16-02-2023',
  '10/10/2023',
  '12-02-2020',
  '13/05/2017',
  '21/04/2016',
  '14/12/2020',
  '09/01/2024',
  '30/11/2025',
  '03-10-2017',
  '24/01/2020',
  '11/22/2016',
  '08/08/2024',
  '19/06/2017',
  '14/07/2021',
  '06/07/2023',
  '06/18/2018',
  '03/28/2021',
  '23/10/2025',
  '10/07/2023',
  '02/04/2023',
  '03/23/2023',
  '16/06/2025',
  '26/10/2021',
  '04/11/2023',
  '04/22/2021',
  '02-02-2023',
  '23/11/2017',
  '02-09-2020',
  '26/08/2017',
  '20-01-2018',
  '05-05-2016',
  '04/18/2018',
  '22/11/2023',
  '05-10-2022',
  '14/04/2024',
  '10/10/2017',
  '06/07/2019',
  '13-10-2023',
  '23/08/2018',
  '09/10/2019',
  '15-03-2018',
  '03/09/2021',
  '10/12/2025',
  '06/10/2024',
  '03/08/2018',
  '12/04/2018',
  '03/01/2023',
  '22/11/2020',
  '02/23/2018',
  '17/04/2019',
  '22-05-2017',
  '14-09-2019',
  '11/06/2015',
  '05/09/2016',
  '30/05/2020',
  '28-08-2022',
  '21/10/2022',
  '10/08/2024',
  '28/02/2019',
  '04-05-2022',
  '18/08/2021',
  '03/10/2021',
  '30/08/2025',
  '07-02-2017',
  '20/02/2025',
  '06/02/2018',
  '30-09-2018',
  '05/11/2016',
  '25-09-2018',
  '25-03-2022',
  '03-07-2021',
  '13-03-2023',
  '11/13/2022',
  '06/13/2020',
  '31-08-2017',
  '01/03/2021',
  '02/07/2021',
  '03/01/2019',
  '29-10-2022',
  '02/17/2018',
  '23/05/2019',
  '03/06/2017',
  '27-02-2025',
  '14-11-2020',
  '07-07-2017',
  '24/03/2022',
  '05/06/2017',
  '02-04-2021',
  '10/06/2023',
  '20/06/2016',
  '08/19/2020',
  '22-12-2019',
  '01-07-2021',
  '10/06/2025',
  '02/21/2019',
  '01/05/2020',
  '07/10/2019',
  '17/08/2024',
  '13-02-2023',
  '03/01/2017',
  '03/01/2021',
  '25/04/2023',
  '16/09/2021',
  '20/11/2019',
  '12/21/2019',
  '26/04/2021',
  '12/03/2023',
  '08/06/2024',
  '10-12-2024',
  '01/08/2021',
  '27/10/2021',
  '03-05-2019',
  '02/09/2025',
  '07-11-2024',
  '02-06-2025',
  '10-03-2021',
  '22/08/2017',
  '02/24/2019',
  '08/03/2023',
  '28-08-2025',
  '12/16/2020',
  '12/02/2016',
  '11-11-2020',
  '29/11/2025',
  '17/05/2023',
  '02/09/2019',
  '06/04/2021',
  '09/14/2021',
  '23/10/2023',
  '18/04/2023',
  '12-07-2022',
  '10/10/2016',
  '03-02-2022',
  '18-12-2021',
  '21-05-2025',
  '03-11-2018',
  '31-05-2018',
  '23/03/2020',
  '22-10-2018',
  '14/01/2024',
  '09/07/2022',
  '03/06/2020',
  '30-12-2017',
  '28/09/2023',
  '13-06-2019',
  '21/09/2019',
  '14-11-2025',
  '12/22/2020',
  '26/01/2019',
  '29/12/2024',
  '03-08-2024',
  '27-03-2020',
  '24-09-2017',
  '15-07-2022',
  '02/02/2017',
  '04/20/2024',
  '01/08/2022',
  '27-05-2016',
  '30-12-2020',
  '15-08-2021',
  '02/25/2025',
  '11-05-2023',
  '08/21/2022',
  '07/07/2021',
  '05/16/2020',
  '09/02/2016',
  '24-09-2023',
  '09/05/2018',
  '01-12-2020',
  '11/18/2024',
  '11-04-2019',
  '18/07/2015',
  '09/30/2017',
  '30-04-2021',
  '12-11-2022',
  '21/08/2024',
  '11/06/2019'])

In [18]:
import pandas as pd
path = r"C:\Users\kanna\Downloads\amazon_india_complete_2015_2025.csv.csv"
raw = pd.read_csv(path, dtype=str, usecols=['order_date'])
s = raw['order_date'].astype(str)

# 1) DD-MM-YYYY and DD/MM/YYYY
mask_dd = s.str.match(r'^\d{2}[-/]\d{2}[-/]\d{4}$', na=False) & pd.to_datetime(s, dayfirst=True, errors='coerce').notna()
parsed_dd = pd.to_datetime(s[mask_dd], format=None, dayfirst=True, errors='coerce')

# 2) MM/DD/YYYY (month-first)
mask_md = s.str.match(r'^\d{2}/\d{2}/\d{4}$', na=False) & pd.to_datetime(s, dayfirst=False, errors='coerce').notna()
parsed_md = pd.to_datetime(s[mask_md], format='%m/%d/%Y', errors='coerce')

# 3) Explicitly assign back into a clean column
clean = pd.Series(pd.NaT, index=s.index)
clean.loc[mask_dd] = parsed_dd
clean.loc[mask_md] = parsed_md

# 4) For any remaining, try common explicit formats
remaining = clean.isna()
formats = ['%d-%m-%Y','%d/%m/%Y','%m/%d/%Y','%d%m%Y','%Y-%m-%d']
for fmt in formats:
    if remaining.any():
        parsed = pd.to_datetime(s[remaining], format=fmt, errors='coerce')
        clean.loc[remaining] = parsed
        remaining = clean.isna()

# 5) Result check
clean.isna().sum(), clean.dropna().head()

C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\2288785733.py:7: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  mask_dd = s.str.match(r'^\d{2}[-/]\d{2}[-/]\d{4}$', na=False) & pd.to_datetime(s, dayfirst=True, errors='coerce').notna()

(np.int64(0),
 0   2023-07-23
 1   2021-07-20
 2   2017-11-16
 3   2020-05-04
 4   2018-10-09
 dtype: datetime64[ns])

In [19]:
df = pd.read_csv(path, dtype=str)         # reload full DF
df['order_date'] = clean                  # assign parsed datetimes (NaT where unparsed)
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')  # ensure dtype
df['order_date'].isna().sum()             # remaining failures

np.int64(0)

In [20]:
df['order_date'] = clean  # if clean is the parsed Series aligned by index
df['order_date'] = pd.to_datetime(df['order_date'], errors='coerce')

In [21]:
df['order_year']   = df['order_date'].dt.year
df['order_month']  = df['order_date'].dt.month
df['order_day']    = df['order_date'].dt.day
df['order_quarter']= df['order_date'].dt.to_period('Q').astype(str)

In [22]:
df.to_parquet('cleaned_transactions.parquet', index=False)
# or df.to_csv('cleaned_transactions.csv', index=False)

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - Missing optional dependency 'pyarrow'. pyarrow is required for parquet support. Use pip or conda to install pyarrow.
 - Missing optional dependency 'fastparquet'. fastparquet is required for parquet support. Use pip or conda to install fastparquet.

In [23]:
df.info()
df['order_date'].isna().sum()   # should be 0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1127609 entries, 0 to 1127608
Data columns (total 35 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   transaction_id          1127609 non-null  object
 1   order_date              1127609 non-null  datetime64[ns]
 2   customer_id             1127609 non-null  object
 3   product_id              1127609 non-null  object
 4   product_name            1127609 non-null  object
 5   category                1127609 non-null  object
 6   subcategory             1127609 non-null  object
 7   brand                   1127609 non-null  object
 8   original_price_inr      1127609 non-null  object
 9   discount_percent        1127609 non-null  object
 10  discounted_price_inr    1127609 non-null  object
 11  quantity                1127609 non-null  object
 12  subtotal_inr            1127609 non-null  object
 13  delivery_charges        1037408 non-null  object
 14  final_amount_inr        1127609 non-null  object
 15  customer_city           1127609 non-null  object
 16  customer_state          1127609 non-null  object
 17  customer_tier           1127609 non-null  object
 18  customer_spending_tier  1127609 non-null  object
 19  customer_age_group      992294 non-null   object
 20  payment_method          1127609 non-null  object
 21  delivery_days           1127609 non-null  object
 22  delivery_type           1127609 non-null  object
 23  is_prime_member         1127609 non-null  object
 24  is_festival_sale        1127609 non-null  object
 25  festival_name           349873 non-null   object
 26  customer_rating         785913 non-null   object
 27  return_status           1127609 non-null  object
 28  order_month             1127609 non-null  int32
 29  order_year              1127609 non-null  int32
 30  order_quarter           1127609 non-null  object
 31  product_weight_kg       1127609 non-null  object
 32  is_prime_eligible       1127609 non-null  object
 33  product_rating          1127609 non-null  object
 34  order_day               1127609 non-null  int32
dtypes: datetime64[ns](1), int32(3), object(31)
memory usage: 288.2+ MB

np.int64(0)

In [24]:
num_cols = ['original_price_inr','discount_percent','discounted_price_inr',
            'quantity','subtotal_inr','delivery_charges','final_amount_inr','product_rating']
for c in num_cols:
    df[c] = df[c].astype(str).str.replace(r'[₹, ]','', regex=True).replace({'': None, 'nan': None})
    df[c] = pd.to_numeric(df[c], errors='coerce')

In [25]:
df['is_prime_member'] = df['is_prime_member'].astype(str).str.lower().map({'yes':True,'y':True,'true':True,'1':'True',
                                                                           'no':False,'n':False,'false':False,'0':'False'}).fillna(False)
df['payment_method'] = df['payment_method'].str.strip().str.title()
df['customer_city'] = df['customer_city'].str.strip().str.title()

In [26]:
df['delivery_charges'].fillna(0, inplace=True)                 # if missing implies free
df['customer_age_group'].fillna('Unknown', inplace=True)
df['festival_name'].fillna('No Festival', inplace=True)
# rating: fill by product median
df['product_rating'] = df['product_rating'].fillna(df.groupby('product_id')['product_rating'].transform('median'))

C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\690656804.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['delivery_charges'].fillna(0, inplace=True)                 # if missing implies free
C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\690656804.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['customer_age_group'].fillna('Unknown', inplace=True)
C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\690656804.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['festival_name'].fillna('No Festival', inplace=True)

In [27]:
df['delivery_charges'] = df['delivery_charges'].fillna(0)
df['customer_age_group'] = df['customer_age_group'].fillna('Unknown')
df['festival_name'] = df['festival_name'].fillna('No Festival')

# ratings: compute median per product and assign
med = df.groupby('product_id')['product_rating'].transform('median')
df['product_rating'] = df['product_rating'].fillna(med)

In [28]:
num_cols = ['original_price_inr','discount_percent','discounted_price_inr',
            'quantity','subtotal_inr','delivery_charges','final_amount_inr','product_rating']
for c in num_cols:
    df[c] = df[c].astype(str).str.replace(r'[₹, ]','', regex=True).replace({'': None, 'nan': None})
    df[c] = pd.to_numeric(df[c], errors='coerce')

In [29]:
df['is_prime_member'] = df['is_prime_member'].astype(str).str.lower().map(
    {'yes': True,'y': True,'true': True,'1': True,'no': False,'n': False,'false': False,'0': False}
).fillna(False)

cat_cols = ['customer_city','customer_state','category','subcategory','brand','payment_method','customer_tier','customer_spending_tier']
for c in cat_cols:
    df[c] = df[c].astype(str).str.strip().str.title().replace({'Nan':'Unknown','None':'Unknown'})

In [30]:
# consistency: quantity * discounted_price ≈ subtotal
mask = df['quantity'].notna() & df['discounted_price_inr'].notna() & df['subtotal_inr'].notna()
( (df.loc[mask,'quantity'] * df.loc[mask,'discounted_price_inr']).round(2)
  .sub(df.loc[mask,'subtotal_inr']).abs().sum() )

# negative checks
(df.select_dtypes(include='number') < 0).sum()

original_price_inr      2792
discount_percent           0
discounted_price_inr       0
quantity                   0
subtotal_inr               0
delivery_charges           0
final_amount_inr           0
order_month                0
order_year                 0
product_rating             0
order_day                  0
dtype: int64

In [31]:
dups = df.duplicated(subset=['transaction_id']).sum()
# if any:
df = df.drop_duplicates(subset=['transaction_id'])

In [32]:
def cap_iqr(s):
    q1,q3 = s.quantile(0.25), s.quantile(0.75)
    iqr = q3-q1
    return s.clip(lower=q1-1.5*iqr, upper=q3+1.5*iqr)
df['final_amount_inr_clean'] = cap_iqr(df['final_amount_inr'])

In [33]:
df['order_year'] = df['order_date'].dt.year
df['order_month'] = df['order_date'].dt.month
df['order_weekday'] = df['order_date'].dt.day_name()
df['is_weekend'] = df['order_weekday'].isin(['Saturday','Sunday'])

In [34]:
# clean price-like columns (if not done)
price_cols = ['original_price_inr','discounted_price_inr','subtotal_inr','final_amount_inr','delivery_charges']
for c in price_cols:
    df[c] = df[c].astype(str).str.replace(r'[₹, ]','', regex=True).replace({'': None, 'nan': None})
    df[c] = pd.to_numeric(df[c], errors='coerce')

# impute small-missing price values by product median
df['original_price_inr'] = df['original_price_inr'].fillna(df.groupby('product_id')['original_price_inr'].transform('median'))
df['delivery_charges'] = df['delivery_charges'].fillna(0)

In [35]:
df['is_prime_member'] = df['is_prime_member'].astype(str).str.lower().map(
    {'yes':True,'y':True,'true':True,'1':True,'no':False,'n':False,'false':False,'0':False}
).fillna(False)

cat_cols = ['customer_city','customer_state','category','subcategory','brand','payment_method','customer_tier','customer_spending_tier']
for c in cat_cols:
    df[c] = df[c].astype(str).str.strip().str.title().replace({'Nan':'Unknown','None':'Unknown'})

In [36]:
# subtotal vs quantity * discounted_price
mask = df[['quantity','discounted_price_inr','subtotal_inr']].notna().all(axis=1)
err_sum = ((df.loc[mask,'quantity'] * df.loc[mask,'discounted_price_inr']) - df.loc[mask,'subtotal_inr']).abs().sum()
print('total inconsistency:', err_sum)

# check negatives and duplicates
print((df.select_dtypes(include='number') < 0).sum())
print('duplicate transaction_id:', df.duplicated(subset=['transaction_id']).sum())

total inconsistency: 672.3700003010264
original_price_inr        2792
discount_percent             0
discounted_price_inr         0
quantity                     0
subtotal_inr                 0
delivery_charges             0
final_amount_inr             0
order_month                  0
order_year                   0
product_rating               0
order_day                    0
final_amount_inr_clean       0
dtype: int64
duplicate transaction_id: 0

In [37]:
df['total_discount'] = df['original_price_inr'] - df['discounted_price_inr']
df['order_value'] = df['final_amount_inr']  # use as main revenue metric
df['cohort_month'] = df.groupby('customer_id')['order_date'].transform('min').dt.to_period('M')
df['days_since_order'] = (pd.Timestamp.today() - df['order_date']).dt.days

In [38]:
cust = df.groupby('customer_id').agg(
    recency = ('order_date', lambda x: (pd.Timestamp.today() - x.max()).days),
    frequency = ('transaction_id', 'nunique'),
    monetary = ('final_amount_inr', 'sum')
).reset_index()

In [45]:
import pandas as pd
df = pd.read_csv(r"C:\Users\kanna\Downloads\amazon_india_complete_2015_2025.csv.csv")  # Adjust path
print(df.head())  # First 5 rows
print(df.info())  # Columns, types, nulls
print(df.isnull().sum())  # Missing values
print(df.duplicated().sum())  # Duplicates

      transaction_id  order_date         customer_id   product_id  \
0  TXN_2023_00063013  2023-07-23  CUST_2023_00018393  PROD_000454
1  TXN_2021_00064486  20-07-2021  CUST_2015_00002865  PROD_000579
2  TXN_2017_00065617  2017-11-16  CUST_2016_00004057  PROD_000295
3  TXN_2020_00054393  2020-05-04  CUST_2020_00014574  PROD_001654
4  TXN_2018_00071646  2018-10-09  CUST_2018_00006275  PROD_000095

                        product_name     category  subcategory      brand  \
0                Vivo Y95 64GB Black  Electronics  Smartphones       Vivo
1        Realme Realme 3 128GB Black  Electronics  Smartphones     Realme
2                  Vivo V7 32GB Blue  Electronics  Smartphones       Vivo
3  Alienware Pavilion 4GB RAM Silver  Electronics      Laptops  Alienware
4    Motorola Moto X Play 16GB White  Electronics  Smartphones   Motorola

  original_price_inr  discount_percent  ...  is_festival_sale  festival_name  \
0           27340.84             21.57  ...             False            NaN
1           32907.49              0.00  ...             False            NaN
2          47,052.18             21.91  ...             False            NaN
3          238725.44             59.60  ...              True    Summer Sale
4           25970.76              0.00  ...             False            NaN

   customer_rating  return_status  order_month order_year order_quarter  \
0              4.0      Delivered            7       2023             3
1              5/5      Delivered            7       2021             3
2              5.0      Delivered           11       2017             4
3        5.0 stars      Delivered            5       2020             2
4              4.0      Delivered           10       2018             4

  product_weight_kg is_prime_eligible product_rating
0              0.20              True            3.5
1              0.21             False            4.5
2              0.24              True            4.3
3              1.85               Yes            3.6
4              0.16             False            3.7

[5 rows x 34 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1127609 entries, 0 to 1127608
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   transaction_id          1127609 non-null  object
 1   order_date              1127609 non-null  object
 2   customer_id             1127609 non-null  object
 3   product_id              1127609 non-null  object
 4   product_name            1127609 non-null  object
 5   category                1127609 non-null  object
 6   subcategory             1127609 non-null  object
 7   brand                   1127609 non-null  object
 8   original_price_inr      1127609 non-null  object
 9   discount_percent        1127609 non-null  float64
 10  discounted_price_inr    1127609 non-null  float64
 11  quantity                1127609 non-null  int64
 12  subtotal_inr            1127609 non-null  float64
 13  delivery_charges        1037408 non-null  float64
 14  final_amount_inr        1127609 non-null  float64
 15  customer_city           1127609 non-null  object
 16  customer_state          1127609 non-null  object
 17  customer_tier           1127609 non-null  object
 18  customer_spending_tier  1127609 non-null  object
 19  customer_age_group      992294 non-null   object
 20  payment_method          1127609 non-null  object
 21  delivery_days           1127609 non-null  object
 22  delivery_type           1127609 non-null  object
 23  is_prime_member         1127609 non-null  object
 24  is_festival_sale        1127609 non-null  object
 25  festival_name           349873 non-null   object
 26  customer_rating         785913 non-null   object
 27  return_status           1127609 non-null  object
 28  order_month             1127609 non-null  int64
 29  order_year              1127609 non-null  int64
 30  order_quarter           1127609 non-null  int64
 31  product_weight_kg       1127609 non-null  float64
 32  is_prime_eligible       1127609 non-null  object
 33  product_rating          1127609 non-null  float64
dtypes: float64(7), int64(4), object(23)
memory usage: 292.5+ MB
None
transaction_id                 0
order_date                     0
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr             0
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
delivery_charges           90201
final_amount_inr               0
customer_city                  0
customer_state                 0
customer_tier                  0
customer_spending_tier         0
customer_age_group        135315
payment_method                 0
delivery_days                  0
delivery_type                  0
is_prime_member                0
is_festival_sale               0
festival_name             777736
customer_rating           341696
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
dtype: int64
0

In [46]:
import pandas as pd

# Function to clean and standardize dates
def clean_date(date_str):
    try:
        return pd.to_datetime(date_str, errors='coerce').strftime('%Y-%m-%d')
    except:
        return None

# Apply cleaning to order_date
df['order_date'] = df['order_date'].apply(clean_date)
df = df.dropna(subset=['order_date'])  # Drop rows with invalid dates

C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\1405801286.py:6: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(date_str, errors='coerce').strftime('%Y-%m-%d')
C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\1405801286.py:6: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  return pd.to_datetime(date_str, errors='coerce').strftime('%Y-%m-%d')

In [47]:
def clean_price(price):
    if isinstance(price, str):
        # Remove ₹, commas, and other non-numeric characters
        price = price.replace('₹', '').replace(',', '').strip()
        try:
            return float(price)
        except:
            return None
    return float(price) if price else None

df['original_price_inr'] = df['original_price_inr'].apply(clean_price)
df = df.dropna(subset=['original_price_inr'])  # Drop invalid prices

In [49]:
df[['order_date']].head(10)
df[['order_date']].tail(10)

         order_date
1127598  2019-10-15
1127599  2020-11-08
1127600  2022-12-29
1127601  2019-10-14
1127602  2020-08-14
1127603  2018-10-16
1127604  2018-07-06
1127605  2022-07-23
1127606  2023-01-07
1127608  2022-12-06

In [50]:
def clean_rating(rating):
    if pd.isna(rating):
        return None
    if isinstance(rating, str):
        if '/' in rating:
            num, denom = rating.split('/')
            return float(num) / float(denom) * 5.0  # Convert to 1-5 scale
        return float(rating.strip(' stars'))
    return float(rating)

df['customer_rating'] = df['customer_rating'].apply(clean_rating)
# Impute missing ratings (e.g., with median)
df['customer_rating'] = df['customer_rating'].fillna(df['customer_rating'].median())

In [51]:
df[['customer_rating']].head(10)
df[['customer_rating']].tail(10)

         customer_rating
1127598              4.0
1127599              4.0
1127600              4.0
1127601              5.0
1127602              4.5
1127603              4.5
1127604              5.0
1127605              4.5
1127606              4.0
1127608              5.0

In [52]:
def clean_boolean(value):
    if isinstance(value, str):
        value = value.strip().lower()
        return True if value in ['true', 'yes', 'y', '1'] else False
    return bool(value)

df['is_festival_sale'] = df['is_festival_sale'].apply(clean_boolean)
df['is_prime_eligible'] = df['is_prime_eligible'].apply(clean_boolean)

In [54]:
df[['is_prime_eligible']].head(10)
df[['is_prime_eligible']].tail(10)

         is_prime_eligible
1127598              False
1127599               True
1127600               True
1127601              False
1127602               True
1127603               True
1127604               True
1127605               True
1127606               True
1127608               True

In [55]:
# Standardize to title case
df['category'] = df['category'].str.title().str.strip()
df['subcategory'] = df['subcategory'].str.title().str.strip()

# Optional: Map variations to a single standard (e.g., 'Electronics & Accessories' -> 'Electronics')
category_mapping = {
    'Electronics & Accessories': 'Electronics',
    'Electronic': 'Electronics'
}
df['category'] = df['category'].replace(category_mapping)

In [58]:
df[['subcategory']].head(20)
df[['subcategory']].tail(20)

                subcategory
1127587         Smartphones
1127588         Smartphones
1127589               Audio
1127590             Tablets
1127591  Tv & Entertainment
1127592         Smartphones
1127593         Smartphones
1127594             Laptops
1127595         Smartphones
1127597  Tv & Entertainment
1127598         Smartphones
1127599         Smartphones
1127600             Tablets
1127601         Smart Watch
1127602         Smartphones
1127603         Smartphones
1127604         Smartphones
1127605             Tablets
1127606             Laptops
1127608               Audio

In [59]:
payment_mapping = {
    'UPI': 'UPI', 'PhonePe': 'UPI', 'GooglePay': 'UPI',
    'Credit Card': 'Credit Card', 'CREDIT_CARD': 'Credit Card', 'CC': 'Credit Card',
    'Cash on Delivery': 'COD', 'C.O.D': 'COD'
}
df['payment_method'] = df['payment_method'].str.strip().replace(payment_mapping)

In [63]:
df[['payment_method']].head(1000)
df[['payment_method']].tail(1020)

        payment_method
1126556            COD
1126557            UPI
1126558            UPI
1126559     Debit Card
1126561     Debit Card
...                ...
1127603     Debit Card
1127604     Debit Card
1127605            UPI
1127606     Debit Card
1127608            UPI

[1020 rows x 1 columns]

In [70]:
# Transpose to view columns more easily
df.T

,0,1,2,3,4,5,6,7,8,9,...,1127598,1127599,1127600,1127601,1127602,1127603,1127604,1127605,1127606,1127608
transaction_id,TXN_2023_00063013,TXN_2021_00064486,TXN_2017_00065617,TXN_2020_00054393,TXN_2018_00071646,TXN_2016_00020663,TXN_2019_00091040,TXN_2020_00052917,TXN_2022_00023262,TXN_2017_00049484,...,TXN_2019_00090058,TXN_2020_00124282,TXN_2022_00117577,TXN_2019_00086569,TXN_2020_00083990,TXN_2018_00075470,TXN_2018_00047331,TXN_2022_00065321,TXN_2023_00057908,TXN_2022_00124835
order_date,2023-07-23,2021-07-20,2017-11-16,2020-05-04,2018-10-09,2016-06-22,2019-10-22,2020-05-24,2022-03-10,2017-09-05,...,2019-10-15,2020-11-08,2022-12-29,2019-10-14,2020-08-14,2018-10-16,2018-07-06,2022-07-23,2023-01-07,2022-12-06
customer_id,CUST_2023_00018393,CUST_2015_00002865,CUST_2016_00004057,CUST_2020_00014574,CUST_2018_00006275,CUST_2016_00006056,CUST_2019_00028838,CUST_2020_00016130,CUST_2015_00001067,CUST_2017_00021979,...,CUST_2019_00030007,CUST_2017_00026004,CUST_2022_00004660,CUST_2016_00003237,CUST_2020_00042010,CUST_2016_00009514,CUST_2017_00025689,CUST_2021_00026763,CUST_2023_00031035,CUST_2022_00042212
product_id,PROD_000454,PROD_000579,PROD_000295,PROD_001654,PROD_000095,PROD_001729,PROD_000178,PROD_000539,PROD_001043,PROD_000247,...,PROD_000286,PROD_000478,PROD_001687,PROD_001891,PROD_000131,PROD_000479,PROD_000009,PROD_001732,PROD_001572,PROD_001764
product_name,Vivo Y95 64GB Black,Realme Realme 3 128GB Black,Vivo V7 32GB Blue,Alienware Pavilion 4GB RAM Silver,Motorola Moto X Play 16GB White,Xiaomi Slate 8GB RAM Silver,Xiaomi Mi 5 64GB Black,OnePlus OnePlus 7 128GB Blue,Realme Realme GT 2 128GB Black,Samsung Galaxy S8+ 32GB White,...,Xiaomi Redmi Note 4 32GB Black,Oppo R17 Pro 256GB Blue,Apple Slate 8GB RAM Silver,Samsung Tracker,Samsung Galaxy S7 64GB White,Oppo R17 Pro 64GB Gold,Apple iPhone 6 Plus 16GB Black,OnePlus iPad 8GB RAM Silver,ASUS Inspiron 8GB RAM Black,JBL Gaming Headset
category,Electronics,Electronics,Electronics,Electronics,Electronics,Electronics,Electronics,Electronics,Electronics,Electronics,...,Electronics,Electronics,Electronics,Electronics,Electronics,Electronics,Electronics,Electronics,Electronics,Electronics
subcategory,Smartphones,Smartphones,Smartphones,Laptops,Smartphones,Tablets,Smartphones,Smartphones,Smartphones,Smartphones,...,Smartphones,Smartphones,Tablets,Smart Watch,Smartphones,Smartphones,Smartphones,Tablets,Laptops,Audio
brand,Vivo,Realme,Vivo,Alienware,Motorola,Xiaomi,Xiaomi,OnePlus,Realme,Samsung,...,Xiaomi,Oppo,Apple,Samsung,Samsung,Oppo,Apple,OnePlus,ASUS,JBL
original_price_inr,27340.84,32907.49,47052.18,238725.44,25970.76,21541.01,39859.05,105554.58,26198.55,121800.87,...,13973.22,36950.16,8134466.0,61116.55,175678.92,30149.16,134278.16,97578.76,105284.29,7092.55
discount_percent,21.57,0.0,21.91,59.6,0.0,59.78,45.78,0.0,64.51,0.0,...,46.47,28.7,0.0,0.0,13.96,41.64,30.83,0.0,43.31,0.0
discounted_price_inr,21442.59,32907.49,36741.38,96456.27,25970.76,8663.17,21610.12,105554.58,9298.46,121800.87,...,7479.54,26345.96,81344.66,61116.55,151157.12,17594.95,92886.49,97578.76,59683.64,7092.55
quantity,1,3,1,1,1,1,1,1,2,3,...,2,1,1,1,2,1,1,1,1,3
subtotal_inr,21442.59,98722.47,36741.38,96456.27,25970.76,8663.17,21610.12,105554.58,18596.91,365402.61,...,14959.09,26345.96,81344.66,61116.55,302314.24,17594.95,92886.49,97578.76,59683.64,21277.65
delivery_charges,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
final_amount_inr,21442.59,98722.47,36741.38,96456.27,25970.76,8663.17,21610.12,105554.58,18596.91,365402.61,...,14959.09,26345.96,81344.66,61116.55,302314.24,17594.95,92886.49,97578.76,59683.64,21277.65
customer_city,Kolkata,Ludhiana,Bangalore,Bangalore,Kochi,Mumbai,Delhi,Mumbai,Kolkata,Mumbai,...,Kolkata,Delhi,Bangalore,Bangalore,Lucknow,Surat,Jaipur,Delhi,Bhubaneswar,Surat
customer_state,West Bengal,Punjab,Karnataka,Karnataka,Kerala,Maharashtra,Delhi,Maharashtra,West Bengal,Maharashtra,...,West Bengal,Delhi,Karnataka,Karnataka,Uttar Pradesh,Gujarat,Rajasthan,Delhi,Odisha,Gujarat
customer_tier,Metro,Tier2,Metro,Metro,Tier2,Metro,Metro,Metro,Metro,Metro,...,Metro,Metro,Metro,Metro,Tier1,Tier1,Tier1,Metro,Tier2,Tier1
customer_spending_tier,Standard,Standard,Premium,Premium,Standard,Standard,Budget,Standard,Standard,Standard,...,Budget,Standard,Standard,Standard,Premium,Standard,Standard,Premium,Standard,Budget
customer_age_group,36-45,NaN,36-45,46-55,18-25,26-35,36-45,NaN,NaN,46-55,...,36-45,36-45,18-25,NaN,46-55,36-45,26-35,36-45,26-35,18-25
payment_method,COD,UPI,Debit Card,UPI,COD,COD,COD,UPI,UPI,COD,...,Credit Card,Credit Card,UPI,COD,UPI,Debit Card,Debit Card,UPI,Debit Card,UPI
delivery_days,3,3,6,3,4,4,5,4,3,6,...,4,4,3,6,1,5,4,1,1,2
delivery_type,Standard,Standard,Standard,Standard,Standard,Standard,Standard,Standard,Standard,Standard,...,Standard,Standard,Standard,Standard,Same Day,Standard,Standard,Same Day,Same Day,Express
is_prime_member,False,False,False,False,False,0,False,False,False,False,...,False,False,True,False,True,False,False,True,1,True
is_festival_sale,False,False,False,True,False,True,True,False,True,False,...,True,False,False,False,False,True,True,False,True,False
festival_name,NaN,NaN,NaN,Summer Sale,NaN,Back to School,Diwali Sale,NaN,Holi Festival,NaN,...,Diwali Sale,NaN,NaN,NaN,NaN,Diwali Sale,Back to School,NaN,Back to School,NaN
customer_rating,4.0,5.0,5.0,5.0,4.0,3.5,4.5,3.5,3.5,5.0,...,4.0,4.0,4.0,5.0,4.5,4.5,5.0,4.5,4.0,5.0
return_status,Delivered,Delivered,Delivered,Delivered,Delivered,Delivered,Delivered,Delivered,Delivered,Delivered,...,Delivered,Delivered,Delivered,Delivered,Delivered,Delivered,Delivered,Delivered,Delivered,Delivered
order_month,7,7,11,5,10,6,10,5,3,9,...,10,11,12,10,8,10,7,7,7,12
order_year,2023,2021,2017,2020,2018,2016,2019,2020,2022,2017,...,2019,2020,2022,2019,2020,2018,2018,2022,2023,2022
order_quarter,3,3,4,2,4,2,4,2,1,3,...,4,4,4,4,3,4,3,3,3,4
product_weight_kg,0.2,0.21,0.24,1.85,0.16,0.33,0.24,0.21,0.18,0.19,...,0.22,0.16,0.63,0.04,0.25,0.16,0.17,0.58,1.37,0.71
is_prime_eligible,True,False,True,True,False,True,True,True,True,True,...,False,True,True,False,True,True,True,True,True,True
product_rating,3.5,4.5,4.3,3.6,3.7,4.5,3.7,3.7,3.2,4.3,...,3.8,4.0,4.5,4.4,4.1,4.4,3.6,4.6,4.2,3.3

In [71]:
def clean_delivery(d):
    if isinstance(d, str):
        if 'Same' in d: return 0
        elif '-' in d: return (int(d.split('-')[0]) + int(d.split('-')[1].split()[0])) / 2
    return abs(float(d)) if pd.notnull(d) else 3  # Cap at reasonable
df['delivery_days'] = df['delivery_days'].apply(clean_delivery)
df = df[df['delivery_days'] <= 30]  # Remove unrealistic

ValueError: invalid literal for int() with base 10: ''

In [72]:
print(df['delivery_days'].unique())

['3' '6' '4' '5' '2' '1' 'Same Day' '1-2 days' '7' '-1' 'Express' '15' '0']

In [73]:
import pandas as pd
import numpy as np

# Sample function to clean delivery_days
def clean_delivery_days(value):
    if pd.isna(value):
        return None
    if isinstance(value, str):
        value = value.lower().strip()
        if value == 'same day':
            return 0
        if '-' in value:
            # Handle ranges like '1-2 days'
            low, high = map(float, value.split('-')[0:2])
            return (low + high) / 2
        try:
            return float(value.replace(' days', ''))
        except:
            return None
    if isinstance(value, (int, float)):
        if value < 0:
            return None  # Mark negative values as invalid
        if value > 30:  # Cap unrealistic values
            return None
        return value
    return None

# Apply cleaning
df['delivery_days'] = df['delivery_days'].apply(clean_delivery_days)

# Impute missing values with median of valid delivery days
median_days = df['delivery_days'].median()
df['delivery_days'] = df['delivery_days'].fillna(median_days)

# Convert to integer
df['delivery_days'] = df['delivery_days'].astype(int)

# Verify cleaning
print(df['delivery_days'].describe())

ValueError: could not convert string to float: '2 days'

In [74]:
import pandas as pd
import numpy as np

# Updated function to clean delivery_days
def clean_delivery_days(value):
    if pd.isna(value):
        return None
    if isinstance(value, str):
        value = value.lower().strip()
        if value == 'same day':
            return 0
        if '-' in value:
            # Handle ranges like '1-2 days'
            try:
                parts = value.split('-')
                low, high = map(float, [p.replace('days', '').strip() for p in parts[0:2]])
                return (low + high) / 2
            except:
                return None
        if 'days' in value:
            # Handle formats like '2 days'
            try:
                return float(value.replace('days', '').strip())
            except:
                return None
        try:
            return float(value)
        except:
            return None
    if isinstance(value, (int, float)):
        if value < 0 or value > 30:  # Handle negative and unrealistic values
            return None
        return value
    return None

# Apply cleaning
df['delivery_days'] = df['delivery_days'].apply(clean_delivery_days)

# Impute missing values with median of valid delivery days
median_days = df['delivery_days'].median()
df['delivery_days'] = df['delivery_days'].fillna(median_days)

# Convert to integer
df['delivery_days'] = df['delivery_days'].astype(int)

# Verify cleaning
print(df['delivery_days'].describe())
print(df['delivery_days'].head())

count    1.093979e+06
mean     3.331288e+00
std      1.751024e+00
min      0.000000e+00
25%      2.000000e+00
50%      3.000000e+00
75%      4.000000e+00
max      1.500000e+01
Name: delivery_days, dtype: float64
0    3
1    3
2    6
3    3
4    4
Name: delivery_days, dtype: int64

In [75]:
df[['delivery_days']].head(10)
df[['delivery_days']].tail(10)

         delivery_days
1127598              4
1127599              4
1127600              3
1127601              6
1127602              1
1127603              5
1127604              4
1127605              1
1127606              1
1127608              2

In [76]:
# Check for duplicates
duplicate_cols = ['customer_id', 'product_id', 'order_date', 'final_amount_inr']
duplicates = df[df.duplicated(subset=duplicate_cols, keep=False)]

# Print duplicate count
print(f"Number of duplicate rows: {len(duplicates)}")
print(duplicates[duplicate_cols + ['transaction_id']].head())

# Handle duplicates (assume no quantity column unless confirmed)
if 'quantity' in df.columns:
    df = df.drop_duplicates(subset=duplicate_cols + ['quantity'], keep='first')
else:
    df = df.drop_duplicates(subset=duplicate_cols + ['transaction_id'], keep='first')

# Verify
print(f"Rows after duplicate handling: {len(df)}")

Number of duplicate rows: 10876
            customer_id   product_id  order_date  final_amount_inr  \
349  CUST_2024_00024541  PROD_000413  2024-01-24          22798.53
450  CUST_2017_00021465  PROD_000298  2017-11-23          55942.89
535  CUST_2023_00001896  PROD_000328  2023-09-16          24435.67
550  CUST_2019_00000663  PROD_000582  2019-03-16          28415.27
567  CUST_2019_00005347  PROD_001636  2019-05-15          55983.74

            transaction_id
349      TXN_2024_00000680
450      TXN_2017_00062563
535  TXN_2023_00085956_DUP
550      TXN_2019_00019444
567      TXN_2019_00037323
Rows after duplicate handling: 1088541

In [77]:
# Calculate IQR for original_price_inr
Q1 = df['original_price_inr'].quantile(0.25)
Q3 = df['original_price_inr'].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = df[(df['original_price_inr'] < lower_bound) | (df['original_price_inr'] > upper_bound)]
print(f"Number of price outliers: {len(outliers)}")

# Category-specific price caps
price_caps = {
    'Smartphones': 150000,
    'Laptops': 300000
}

# Correct outliers
def correct_price(row):
    price = row['original_price_inr']
    category = row['subcategory']
    if price > upper_bound:
        corrected_price = price / 100  # Fix decimal point errors
        cap = price_caps.get(category, 150000)
        if corrected_price <= cap:
            return corrected_price
        return cap
    return price

df['original_price_inr'] = df.apply(correct_price, axis=1)

# Validate with final_amount_inr
df['original_price_inr'] = df['original_price_inr'].where(
    df['original_price_inr'] >= df['final_amount_inr'],
    df['final_amount_inr'] / (1 - df['discount_percent'] / 100)
)

# Verify
print(df['original_price_inr'].describe())

Number of price outliers: 39961
count    1.088541e+06
mean     8.147684e+04
std      7.764060e+04
min      1.067270e+03
25%      3.138596e+04
50%      5.395467e+04
75%      1.065641e+05
max      1.262114e+06
Name: original_price_inr, dtype: float64

C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\3675797223.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['original_price_inr'] = df.apply(correct_price, axis=1)
C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\3675797223.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['original_price_inr'] = df['original_price_inr'].where(

In [78]:
payment_mapping = {
    'UPI': 'UPI', 'PhonePe': 'UPI', 'GooglePay': 'UPI',
    'Credit Card': 'Credit Card', 'CREDIT_CARD': 'Credit Card', 'CC': 'Credit Card',
    'Cash on Delivery': 'COD', 'C.O.D': 'COD'
}
df['payment_method'] = df['payment_method'].str.strip().replace(payment_mapping)

C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\477152931.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['payment_method'] = df['payment_method'].str.strip().replace(payment_mapping)

In [79]:
df[['payment_method']].head(10)
df[['payment_method']].tail(10)

        payment_method
1127598    Credit Card
1127599    Credit Card
1127600            UPI
1127601            COD
1127602            UPI
1127603     Debit Card
1127604     Debit Card
1127605            UPI
1127606     Debit Card
1127608            UPI

In [80]:
df.describe()

,original_price_inr,discount_percent,discounted_price_inr,quantity,subtotal_inr,delivery_charges,final_amount_inr,delivery_days,customer_rating,order_month,order_year,order_quarter,product_weight_kg,product_rating
count,1.088541e+06,1.088541e+06,1.088541e+06,1.088541e+06,1.088541e+06,1.001478e+06,1.088541e+06,1.088541e+06,1.088541e+06,1.088541e+06,1.088541e+06,1.088541e+06,1.088541e+06,1.088541e+06
mean,8.147684e+04,1.741770e+01,5.454002e+04,1.250107e+00,6.819031e+04,3.195277e-04,6.819031e+04,3.331319e+00,4.367947e+00,6.940443e+00,2.020637e+03,2.645852e+00,7.811905e-01,3.975234e+00
std,7.764060e+04,2.055097e+01,4.581317e+04,5.365230e-01,6.894774e+04,1.130532e-01,6.894773e+04,1.751085e+00,4.859180e-01,3.539215e+00,2.691033e+00,1.140829e+00,3.676907e+00,4.536427e-01
min,1.067270e+03,0.000000e+00,3.443300e+02,1.000000e+00,3.443300e+02,0.000000e+00,3.443300e+02,0.000000e+00,3.000000e+00,1.000000e+00,2.015000e+03,1.000000e+00,3.000000e-02,3.000000e+00
25%,3.138596e+04,0.000000e+00,2.277949e+04,1.000000e+00,2.521799e+04,0.000000e+00,2.521799e+04,2.000000e+00,4.000000e+00,4.000000e+00,2.019000e+03,2.000000e+00,1.800000e-01,3.600000e+00
50%,5.395467e+04,1.036000e+01,3.801025e+04,1.000000e+00,4.474521e+04,0.000000e+00,4.474521e+04,3.000000e+00,4.500000e+00,7.000000e+00,2.021000e+03,3.000000e+00,2.100000e-01,4.000000e+00
75%,1.065641e+05,2.841000e+01,7.411956e+04,1.000000e+00,8.853546e+04,0.000000e+00,8.853546e+04,4.000000e+00,4.500000e+00,1.000000e+01,2.023000e+03,4.000000e+00,2.400000e-01,4.400000e+00
max,1.262114e+06,7.000000e+01,4.207048e+05,3.000000e+00,1.262114e+06,4.000000e+01,1.262114e+06,1.500000e+01,5.000000e+00,1.200000e+01,2.025000e+03,4.000000e+00,4.426000e+01,4.800000e+00

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1088541 entries, 0 to 1127608
Data columns (total 34 columns):
 #   Column                  Non-Null Count    Dtype
---  ------                  --------------    -----
 0   transaction_id          1088541 non-null  object
 1   order_date              1088541 non-null  object
 2   customer_id             1088541 non-null  object
 3   product_id              1088541 non-null  object
 4   product_name            1088541 non-null  object
 5   category                1088541 non-null  object
 6   subcategory             1088541 non-null  object
 7   brand                   1088541 non-null  object
 8   original_price_inr      1088541 non-null  float64
 9   discount_percent        1088541 non-null  float64
 10  discounted_price_inr    1088541 non-null  float64
 11  quantity                1088541 non-null  int64
 12  subtotal_inr            1088541 non-null  float64
 13  delivery_charges        1001478 non-null  float64
 14  final_amount_inr        1088541 non-null  float64
 15  customer_city           1088541 non-null  object
 16  customer_state          1088541 non-null  object
 17  customer_tier           1088541 non-null  object
 18  customer_spending_tier  1088541 non-null  object
 19  customer_age_group      957938 non-null   object
 20  payment_method          1088541 non-null  object
 21  delivery_days           1088541 non-null  int64
 22  delivery_type           1088541 non-null  object
 23  is_prime_member         1088541 non-null  object
 24  is_festival_sale        1088541 non-null  bool
 25  festival_name           337669 non-null   object
 26  customer_rating         1088541 non-null  float64
 27  return_status           1088541 non-null  object
 28  order_month             1088541 non-null  int64
 29  order_year              1088541 non-null  int64
 30  order_quarter           1088541 non-null  int64
 31  product_weight_kg       1088541 non-null  float64
 32  is_prime_eligible       1088541 non-null  bool
 33  product_rating          1088541 non-null  float64
dtypes: bool(2), float64(9), int64(5), object(18)
memory usage: 276.1+ MB

In [83]:
df.isnull()

,transaction_id,order_date,customer_id,product_id,product_name,category,subcategory,brand,original_price_inr,discount_percent,...,is_festival_sale,festival_name,customer_rating,return_status,order_month,order_year,order_quarter,product_weight_kg,is_prime_eligible,product_rating
0,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1127603,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1127604,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1127605,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1127606,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1127608,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [84]:
import pandas as pd

# Check null values in the DataFrame
null_counts = df.isna().sum()
print("Null values per column:")
print(null_counts)

# Check total null values
total_nulls = df.isna().sum().sum()
print(f"\nTotal null values in DataFrame: {total_nulls}")

Null values per column:
transaction_id                 0
order_date                     0
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr             0
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
delivery_charges           87063
final_amount_inr               0
customer_city                  0
customer_state                 0
customer_tier                  0
customer_spending_tier         0
customer_age_group        130603
payment_method                 0
delivery_days                  0
delivery_type                  0
is_prime_member                0
is_festival_sale               0
festival_name             750872
customer_rating                0
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
dtype: int64

Total null values in DataFrame: 968538

In [86]:
import pandas as pd
df   # Adjust path
print(df.isnull().sum())  # Confirm nulls match your counts
print(f"Total rows: {len(df)}")

transaction_id                 0
order_date                     0
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr             0
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
delivery_charges           87063
final_amount_inr               0
customer_city                  0
customer_state                 0
customer_tier                  0
customer_spending_tier         0
customer_age_group        130603
payment_method                 0
delivery_days                  0
delivery_type                  0
is_prime_member                0
is_festival_sale               0
festival_name             750872
customer_rating                0
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
dtype: int64
Total rows: 1088541

In [87]:
df.isnull().sum()

transaction_id                 0
order_date                     0
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr             0
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
delivery_charges           87063
final_amount_inr               0
customer_city                  0
customer_state                 0
customer_tier                  0
customer_spending_tier         0
customer_age_group        130603
payment_method                 0
delivery_days                  0
delivery_type                  0
is_prime_member                0
is_festival_sale               0
festival_name             750872
customer_rating                0
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
dtype: int64

In [88]:
df.isnull().T

,0,1,2,3,4,5,6,7,8,9,...,1127598,1127599,1127600,1127601,1127602,1127603,1127604,1127605,1127606,1127608
transaction_id,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
order_date,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
customer_id,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
product_id,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
product_name,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
category,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
subcategory,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
brand,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
original_price_inr,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
discount_percent,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
discounted_price_inr,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
quantity,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
subtotal_inr,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
delivery_charges,False,False,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
final_amount_inr,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
customer_city,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
customer_state,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
customer_tier,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
customer_spending_tier,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
customer_age_group,False,True,False,False,False,False,False,True,True,False,...,False,False,False,True,False,False,False,False,False,False
payment_method,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
delivery_days,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
delivery_type,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
is_prime_member,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
is_festival_sale,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
festival_name,True,True,True,False,True,False,False,True,False,True,...,False,True,True,True,True,False,False,True,False,True
customer_rating,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
return_status,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
order_month,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
order_year,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
order_quarter,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
product_weight_kg,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
is_prime_eligible,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
product_rating,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [89]:
# Check distribution
print(df['delivery_charges'].describe())
# Simple median imputation
df['delivery_charges'].fillna(df['delivery_charges'].median(), inplace=True)
# Optional: Context-based imputation
print(df.groupby('delivery_type')['delivery_charges'].median())  # Check for patterns
df['delivery_charges'] = df.groupby('delivery_type')['delivery_charges'].transform(lambda x: x.fillna(x.median()))

count    1.001478e+06
mean     3.195277e-04
std      1.130532e-01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      4.000000e+01
Name: delivery_charges, dtype: float64
delivery_type
Express     0.0
Same Day    0.0
Standard    0.0
Name: delivery_charges, dtype: float64

C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\3821028528.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['delivery_charges'].fillna(df['delivery_charges'].median(), inplace=True)
C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\3821028528.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['delivery_charges'].fillna(df['delivery_charges'].median(), inplace=True)
C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\3821028528.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['delivery_charges'] = df.groupby('delivery_type')['delivery_charges'].transform(lambda x: x.fillna(x.median()))

In [90]:
print(df['delivery_charges'].isnull().sum())  # Should be 0
print(df['delivery_charges'].describe())  # Confirm reasonable values

0
count    1.088541e+06
mean     2.939715e-04
std      1.084379e-01
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      4.000000e+01
Name: delivery_charges, dtype: float64

In [91]:
# Check distribution
print(df['customer_age_group'].value_counts(dropna=False))
# Impute with mode
df['customer_age_group'].fillna(df['customer_age_group'].mode()[0], inplace=True)
# Alternative: Use 'Unknown'
# df['customer_age_group'].fillna('Unknown', inplace=True)

customer_age_group
26-35    335837
18-25    305440
36-45    192281
NaN      130603
46-55     95550
55+       28830
Name: count, dtype: int64

C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\3405559756.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['customer_age_group'].fillna(df['customer_age_group'].mode()[0], inplace=True)
C:\Users\kanna\AppData\Local\Temp\ipykernel_20996\3405559756.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['customer_age_group'].fillna(df['customer_age_group'].mode()[0], inplace=True)

In [92]:
print(df['customer_age_group'].isnull().sum())  # Should be 0
print(df['customer_age_group'].value_counts())  # Check distribution

0
customer_age_group
26-35    466440
18-25    305440
36-45    192281
46-55     95550
55+       28830
Name: count, dtype: int64

In [93]:
df.isnull().sum()

transaction_id                 0
order_date                     0
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr             0
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
delivery_charges               0
final_amount_inr               0
customer_city                  0
customer_state                 0
customer_tier                  0
customer_spending_tier         0
customer_age_group             0
payment_method                 0
delivery_days                  0
delivery_type                  0
is_prime_member                0
is_festival_sale               0
festival_name             750872
customer_rating                0
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
dtype: int64

In [96]:
print(df['customer_city'].head(10))  # Should be 0
print(df['customer_city'].tail(10))  # Check distribution

0      Kolkata
1     Ludhiana
2    Bangalore
3    Bangalore
4        Kochi
5       Mumbai
6        Delhi
7       Mumbai
8      Kolkata
9       Mumbai
Name: customer_city, dtype: object
1127598        Kolkata
1127599          Delhi
1127600      Bangalore
1127601      Bangalore
1127602        Lucknow
1127603          Surat
1127604         Jaipur
1127605          Delhi
1127606    Bhubaneswar
1127608          Surat
Name: customer_city, dtype: object

In [97]:
df = df.drop_duplicates(subset=['customer_id', 'product_id', 'order_date', 'final_amount_inr'], keep='first')
print(f"Rows after deduplication: {len(df)}")

Rows after deduplication: 1088541

In [98]:
df.to_csv('cleaned_data.csv', index=False)
print(df.isnull().sum())  # Confirm no nulls
print(f"Final rows: {len(df)}")  # Should be close to 1,088,541

transaction_id                 0
order_date                     0
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr             0
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
delivery_charges               0
final_amount_inr               0
customer_city                  0
customer_state                 0
customer_tier                  0
customer_spending_tier         0
customer_age_group             0
payment_method                 0
delivery_days                  0
delivery_type                  0
is_prime_member                0
is_festival_sale               0
festival_name             750872
customer_rating                0
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
dtype: int64
Final rows: 1088541

In [99]:
C:\Users\kanna\Downloads

SyntaxError: unexpected character after line continuation character (2722267978.py, line 1)

In [101]:
import pandas as pd
import os

# Assuming df is your cleaned DataFrame
# Example: Load and clean data (replace with your actual cleaning code)
# df = pd.read_csv('data/amazon_india_complete_2015_2025.csv')
# ... your cleaning steps (e.g., from previous responses: impute delivery_charges with median, customer_age_group with mode)

# Get the Downloads folder path
downloads_path = os.path.join(os.path.expanduser('~'), 'Downloads', 'cleaned_data.csv')

# Save DataFrame to Downloads folder with error handling
try:
    df.to_csv(downloads_path, index=False, encoding='utf-8')
    print(f"Cleaned data saved to: {downloads_path}")
except Exception as e:
    print(f"Error saving file: {e}. Check path, permissions, or disk space.")

# Verify file exists
if os.path.exists(downloads_path):
    print("File successfully saved in Downloads!")
    # Verify row count and nulls
    df_check = pd.read_csv(downloads_path)
    print(f"Rows in saved file: {len(df_check)}")  # Should be ~1,088,541
    print("Null counts:\n", df_check.isnull().sum())
else:
    print("Error: File not saved. Check path or permissions.")

Cleaned data saved to: C:\Users\kanna\Downloads\cleaned_data.csv
File successfully saved in Downloads!
Rows in saved file: 1088541
Null counts:
 transaction_id                 0
order_date                     0
customer_id                    0
product_id                     0
product_name                   0
category                       0
subcategory                    0
brand                          0
original_price_inr             0
discount_percent               0
discounted_price_inr           0
quantity                       0
subtotal_inr                   0
delivery_charges               0
final_amount_inr               0
customer_city                  0
customer_state                 0
customer_tier                  0
customer_spending_tier         0
customer_age_group             0
payment_method                 0
delivery_days                  0
delivery_type                  0
is_prime_member                0
is_festival_sale               0
festival_name             750872
customer_rating                0
return_status                  0
order_month                    0
order_year                     0
order_quarter                  0
product_weight_kg              0
is_prime_eligible              0
product_rating                 0
dtype: int64